kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - ls
  - go build -o app .
  - ./app
  - echo -n "0.1" > .tags

- name: docker
  image: plugins/docker
  settings:
    username: kzeeyang
    password: kong519627
    repo: test
