kind: pipeline
name: default

steps:
- name: golang
  image: golang:alpine
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  commands:
  - pwd
  - go build -o app .
  - ls
  - ./app
