kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: golang
  image: golang:alpine
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  commands:
  - pwd
  - go build -o app .
  - ls
  - ./app
  when:
    event:
    - push
