kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/kzeeyang/drone

steps:
- name: test
  image: golang
  commands:
  - ls
  - go get
  - go test
- name: build
  image: golang
  commands:
    - go get
    - go build -o output
    - chmod +x output
- name: run
  image: golang
  commands:
    - go get
    - go build -o output
    - chmod +x output
    - ./output
